version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nestjsdb
      MYSQL_USER: nestjsuser
      MYSQL_PASSWORD: nestjspassword
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    depends_on:
      - db
    image: ${FUN_PROJECT}
    # env_file:
    # - .env
    environment:
      FORBIDDEN_WORDS: halo,tokay,mencret
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: nestjsuser
      DATABASE_PASSWORD: nestjspassword
      DATABASE_NAME: nestjsdb
    ports:
      - '8080:8080'
volumes:
  mysql-data:
